# Generated by Django 6.0.3 on 2026-03-25 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_publicacao',
            field=models.CharField(default=datetime.datetime.now),
        ),
    ]
